# Generated by Django 4.0.2 on 2022-02-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.TextField(default=1, verbose_name='Приоритет'),
            preserve_default=False,
        ),
    ]
